(base) jfrey@jordans-mbp unit_test % python test.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
(base) jfrey@jordans-mbp unit_test % python -m unittest test
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
(base) jfrey@jordans-mbp unit_test % python -m unittest -v test
test_list_int (test.TestSum)
Test that it can sum a list of integers ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
(base) jfrey@jordans-mbp unit_test % python -m unittest discover
..F
======================================================================
FAIL: test_sum_tuple (test_sum_unittest.TestSum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jfrey/Library/CloudStorage/OneDrive-Personal/Documents/Personal_Projects/unit_test/test_sum_unittest.py", line 16, in test_sum_tuple
    self.assertEqual(sum((1, 2, 2)), 6, "Should be 6")
AssertionError: 5 != 6 : Should be 6

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (failures=1)
(base) jfrey@jordans-mbp unit_test % 


























































